import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/fonts";
import Providers from "./providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AddNewPhotoBtn from "@/components/AddNewPhotoBtn";

export const metadata: Metadata = {
  title: "My Own Photo Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased flex flex-col min-h-svh justify-between bg-background dark:bg-dark-background text-foreground dark:text-dark-foreground`}
      >
        <Providers>
          <Header />

          <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
            <AddNewPhotoBtn />
            {children}
          </main>

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
