import type { Metadata } from "next";
import "../styles/globals.css";
import { GeistFont } from "fonts";
import StoreProvider from "components/StoreProvider";
import Header from "components/Header";
import Footer from "components/Footer";
import LocalPreferencesInitializer from "components/LocalPreferencesInitializer";
import AddNewPhotoBtn from "components/AddNewPhotoBtn";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "My Own Photo Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <LocalPreferencesInitializer />
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${GeistFont.className} antialiased flex flex-col min-h-svh justify-between bg-background dark:bg-dark-background text-foreground dark:text-dark-foreground`}
        >
          <Header />
          <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
            {/*TODO: think about where to place this button */}
            <AddNewPhotoBtn />
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
